language: node_js

node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"

addons:
    firefox: "latest"

cache:
    directories:
        node_modules

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - npm run lint
    - npm run mocha
    - npm run karma -- --browsers PhantomJS,ChromeTravis,Firefox
    - npm run build
    - npm run build:dev
