language: node_js

node_js:
  - "6"

addons:
    firefox: "latest"

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - npm run lint -s
    - npm test -s
    - npm run karma:browser -s -- --browsers Firefox
    - npm run build -s
    - npm run build:dev -s
    - npm run mocha:coverage -s
    - npm run karma:coverage -s
